{
    "name": "Crimest System Ver.1.1 CODE:Verdom",
    "planets": [
        {
            "name": "O-01",
            "mass": 5000,
            "position_x": -41412.98828125,
            "position_y": -43416.171875,
            "velocity_x": 66.05561065673828,
            "velocity_y": -63.007850646972656,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-02",
            "mass": 5000,
            "position_x": 41412.98046875,
            "position_y": 43416.1796875,
            "velocity_x": -66.05561828613281,
            "velocity_y": 63.00783920288086,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-03",
            "mass": 5000,
            "position_x": -43416.17578125,
            "position_y": 41412.984375,
            "velocity_x": -63.00784683227539,
            "velocity_y": -66.05561828613281,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-04",
            "mass": 5000,
            "position_x": 43416.1796875,
            "position_y": -41412.98046875,
            "velocity_x": 63.00783920288086,
            "velocity_y": 66.05561828613281,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "KameWaterofBanana",
            "mass": 50000,
            "position_x": -12535.3984375,
            "position_y": -1036.19580078125,
            "velocity_x": 16.42484474182129,
            "velocity_y": -198.70004272460938,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1259352192,
                "radius": 1500,
                "heightRange": 64,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Super",
            "mass": 50000,
            "position_x": -10172.6806640625,
            "position_y": -11546.27734375,
            "velocity_x": 135.25108337402344,
            "velocity_y": -119.16102600097656,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 325555008,
                "radius": 1300,
                "heightRange": 52.999996185302734,
                "waterHeight": 19,
                "waterDepth": 100,
                "temperature": 72.99999237060547,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "bebed",
            "mass": 10000,
            "position_x": 50175.7265625,
            "position_y": 21086.640625,
            "velocity_x": -37.13438034057617,
            "velocity_y": 88.36137390136719,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1352824960,
                "radius": 683,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 50,
                "metalClusters": 50,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Nu",
            "mass": 35000,
            "position_x": 28392.892578125,
            "position_y": 16422.0546875,
            "velocity_x": -61.81611251831055,
            "velocity_y": 106.87688446044922,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 919832448,
                "radius": 1083,
                "heightRange": 52.999996185302734,
                "waterHeight": 31,
                "waterDepth": 100,
                "temperature": 97.99999237060547,
                "metalDensity": 75,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "terrain",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "ZA.KU.RO",
            "mass": 10000,
            "position_x": -556.91015625,
            "position_y": -43591.390625,
            "velocity_x": 107.08570098876953,
            "velocity_y": -1.368101954460144,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 275477696,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 14,
                "metalDensity": 50,
                "metalClusters": 50,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Cookiezi",
            "mass": 5000,
            "position_x": 3400,
            "position_y": -55800,
            "velocity_x": 166.4624786376953,
            "velocity_y": 17.876401901245117,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 714028480,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 60.000003814697266,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Better Discord",
            "mass": 35000,
            "position_x": 77348.0859375,
            "position_y": -62793.67578125,
            "velocity_x": 44.650630950927734,
            "velocity_y": 54.99982833862305,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 885435584,
                "radius": 1300,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 25,
                "metalDensity": 88,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "KM-DOS",
            "mass": 10000,
            "position_x": 55918.52734375,
            "position_y": -67353.75,
            "velocity_x": 63.25208282470703,
            "velocity_y": -32.41548538208008,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1709817984,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 22,
                "metalClusters": 60.000003814697266,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Mojang",
            "mass": 10000,
            "position_x": 79307.5078125,
            "position_y": -60544.078125,
            "velocity_x": 227.28431701660156,
            "velocity_y": -104.0758056640625,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1298502528,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 55,
                "metalClusters": 39,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "HIDEHEAVY",
            "mass": 5000,
            "position_x": 46544.9921875,
            "position_y": -60527.5,
            "velocity_x": 101.90837860107422,
            "velocity_y": 20.665809631347656,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1013600704,
                "radius": 1300,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 25,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "GAITO8.8",
            "mass": 10000,
            "position_x": 70986.3203125,
            "position_y": -56391.484375,
            "velocity_x": 143.4237060546875,
            "velocity_y": 153.1493682861328,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 455745728,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 9,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Minecraft Forge",
            "mass": 5000,
            "position_x": 73957.3125,
            "position_y": -60034.03125,
            "velocity_x": 223.34649658203125,
            "velocity_y": 218.33724975585938,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 624899648,
                "radius": 832,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 36,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}