{
    "name": "Fire Vortex",
    "planets": [
        {
            "name": "FVc",
            "mass": 20000,
            "position_x": -0.00021464782184921205,
            "position_y": 17999.998046875,
            "velocity_x": -166.66665649414062,
            "velocity_y": -0.000009272710485674907,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 15,
            "planet": {
                "seed": 1288960896,
                "radius": 600,
                "heightRange": 50,
                "waterHeight": 40,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "FVc1a",
            "mass": 10000,
            "position_x": 2800.000732421875,
            "position_y": 18000.001953125,
            "velocity_x": -166.66693115234375,
            "velocity_y": 188.982177734375,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 60,
            "planet": {
                "seed": 4,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "FVc1b",
            "mass": 10000,
            "position_x": -2799.998779296875,
            "position_y": 18000,
            "velocity_x": -166.66677856445312,
            "velocity_y": -188.9822998046875,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 60,
            "planet": {
                "seed": 4,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "FVc2a",
            "mass": 10000,
            "position_x": 3700.004150390625,
            "position_y": 18000,
            "velocity_x": -166.666748046875,
            "velocity_y": 164.3988494873047,
            "required_thrust_to_move": 6,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 15,
            "planet": {
                "seed": 396,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "FVc2b",
            "mass": 10000,
            "position_x": -3699.995849609375,
            "position_y": 18000,
            "velocity_x": -166.66671752929688,
            "velocity_y": -164.3990936279297,
            "required_thrust_to_move": 6,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 15,
            "planet": {
                "seed": 396,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "FVb",
            "mass": 10000,
            "position_x": 0,
            "position_y": 12500,
            "velocity_x": -200,
            "velocity_y": -0.000008742276804696303,
            "required_thrust_to_move": 24,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 600,
            "planet": {
                "seed": 4096,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}