{
    "name": "MegaApple Prime",
    "planets": [
        {
            "name": "Zupiter",
            "mass": 50000,
            "position_x": 0.001092784688808024,
            "position_y": 25000,
            "velocity_x": -141.42135620117188,
            "velocity_y": -5.024295866504214e-13,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1582493696,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 88,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zupiter I",
            "mass": 5000,
            "position_x": -0.0002757490146905184,
            "position_y": 22200,
            "velocity_x": -440.228515625,
            "velocity_y": 0.00013298432168085128,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 3,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zupiter II",
            "mass": 5000,
            "position_x": 0.00021381856640800834,
            "position_y": 27800,
            "velocity_x": 157.38580322265625,
            "velocity_y": 0.00010686177120078355,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 3,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zaturn",
            "mass": 50000,
            "position_x": 0,
            "position_y": -35000,
            "velocity_x": 119.52285766601562,
            "velocity_y": 0.000005224510005064076,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 103485968,
                "radius": 2000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 63,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zaturn Enari",
            "mass": 35000,
            "position_x": 0.0006190986023284495,
            "position_y": -31200,
            "velocity_x": -136.9716796875,
            "velocity_y": 0.00003580104385036975,
            "required_thrust_to_move": 8,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1371972352,
                "radius": 600,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 44,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}