{
    "name": "New Age",
    "description": "New Planet appears in 10:00",
    "creator": "Zakuro",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Dark Age",
            "mass": 10000,
            "position_x": -19099.9921875,
            "position_y": -13300.0078125,
            "velocity_x": 83.75636291503906,
            "velocity_y": -120.28156280517578,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 600,
            "max_spawn_delay": 600,
            "planet": {
                "seed": 1451627008,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Dark Age I",
            "mass": 5000,
            "position_x": -20800,
            "position_y": -11700,
            "velocity_x": 70.9632339477539,
            "velocity_y": -126.1568603515625,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 1,
            "planet": {
                "seed": 1532474752,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Ice Age",
            "mass": 10000,
            "position_x": 14699.9990234375,
            "position_y": 10600.0009765625,
            "velocity_x": -97.14915466308594,
            "velocity_y": 134.72567749023438,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 30278028,
                "radius": 500,
                "heightRange": 50,
                "waterHeight": 15.000000953674316,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Ice Age I",
            "mass": 5000,
            "position_x": 12400,
            "position_y": 10600,
            "velocity_x": -97.14908599853516,
            "velocity_y": -12.71630859375,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1509321600,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "New Age",
            "mass": 10000,
            "position_x": 14099.9990234375,
            "position_y": 18599.990234375,
            "velocity_x": -116.63745880126953,
            "velocity_y": 88.41874694824219,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 1,
            "planet": {
                "seed": 984711808,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "New Age I",
            "mass": 5000,
            "position_x": 15899.998046875,
            "position_y": 17199.994140625,
            "velocity_x": -25.72777557373047,
            "velocity_y": 205.30291748046875,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 1,
            "planet": {
                "seed": 244387488,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}