{
    "name": "Pan Oceanic 4",
    "description": "",
    "creator": "​​​Zakuro",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Pangas",
            "mass": 50000,
            "position_x": -20000,
            "position_y": 0,
            "velocity_x": 0.000006911377113283379,
            "velocity_y": -158.11387634277344,
            "required_thrust_to_move": 12,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 1",
            "mass": 10000,
            "position_x": -23000,
            "position_y": 0,
            "velocity_x": -0.000005707014224753948,
            "velocity_y": 130.56126403808594,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 2",
            "mass": 10000,
            "position_x": -24000,
            "position_y": 0,
            "velocity_x": -0.0000040164709389500786,
            "velocity_y": 91.88612365722656,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 3",
            "mass": 10000,
            "position_x": -25000,
            "position_y": 0,
            "velocity_x": -0.000002862786004698137,
            "velocity_y": 65.492919921875,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 4",
            "mass": 10000,
            "position_x": -26000,
            "position_y": 0,
            "velocity_x": -0.0000020111724552407395,
            "velocity_y": 46.01026916503906,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}