{
    "name": "Pan Oceanic 3",
    "description": "",
    "creator": "Zakuro",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Pangas",
            "mass": 50000,
            "position_x": -20000.001953125,
            "position_y": 0.009765625,
            "velocity_x": -0.00007029265543678775,
            "velocity_y": -158.11387634277344,
            "required_thrust_to_move": 12,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 1",
            "mass": 10000,
            "position_x": -23000.001953125,
            "position_y": 0.009765625,
            "velocity_x": -0.00005767426409875043,
            "velocity_y": -446.78900146484375,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 2",
            "mass": 10000,
            "position_x": -17000.001953125,
            "position_y": 0.009670265018939972,
            "velocity_x": -0.00007373502739937976,
            "velocity_y": 130.56126403808594,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 3",
            "mass": 10000,
            "position_x": -24000,
            "position_y": 0,
            "velocity_x": 0.0000063091956690186635,
            "velocity_y": -144.3375701904297,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Pan 4",
            "mass": 10000,
            "position_x": -16000,
            "position_y": 0,
            "velocity_x": 0.0005291305715218186,
            "velocity_y": 91.88604736328125,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 396,
                "radius": 450,
                "heightRange": 35,
                "waterHeight": 42,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}