{
    "name": "The Practice Maximin",
    "description": "LARGEST AND SMALLEST",
    "creator": "Zakuro",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Practice 2000",
            "mass": 10000,
            "position_x": 27775,
            "position_y": -0.002428167499601841,
            "velocity_x": 0.00000586479063713341,
            "velocity_y": 134.1707763671875,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 571419008,
                "radius": 2000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Practice 100",
            "mass": 5000,
            "position_x": 17200,
            "position_y": 0,
            "velocity_x": -0.0000069181319304334465,
            "velocity_y": 65.40936279296875,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1112661120,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}