{
    "name": "WAM System",
    "description": "",
    "creator": "",
    "version": "",
    "planets": [
        {
            "name": "Gas Wam",
            "mass": 50000,
            "position_x": 75699.984375,
            "position_y": -57800.01171875,
            "velocity_x": 43.97032165527344,
            "velocity_y": 57.58740997314453,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1006100224,
                "radius": 2000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Wam Desert",
            "mass": 10000,
            "position_x": 90699.984375,
            "position_y": -55600.00390625,
            "velocity_x": 62.60515594482422,
            "velocity_y": -69.46766662597656,
            "required_thrust_to_move": 10,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1184098176,
                "radius": 1000,
                "heightRange": 55,
                "waterHeight": 46,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 90,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Wam planet",
            "mass": 20000,
            "position_x": 66399.984375,
            "position_y": -56700.01953125,
            "velocity_x": 24.77878189086914,
            "velocity_y": -104.66954803466797,
            "required_thrust_to_move": 10,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 95241472,
                "radius": 1000,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 90,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Dead Wam",
            "mass": 35000,
            "position_x": -99839.9765625,
            "position_y": -65120,
            "velocity_x": 35.382232666015625,
            "velocity_y": -54.2469367980957,
            "required_thrust_to_move": 12,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1001181120,
                "radius": 1200,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 75,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Wam Fire",
            "mass": 10000,
            "position_x": 6300.01708984375,
            "position_y": -24099.9921875,
            "velocity_x": 137.07102966308594,
            "velocity_y": 35.83195877075195,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1601830272,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 75,
                "metalClusters": 75,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Ice Wam",
            "mass": 10000,
            "position_x": 149700,
            "position_y": -56400,
            "velocity_x": 19.710514068603516,
            "velocity_y": 52.31674575805664,
            "required_thrust_to_move": 10,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 177586896,
                "radius": 800,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 80,
                "metalClusters": 80,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 8,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Florence",
            "mass": 5000,
            "position_x": 149600,
            "position_y": -53800,
            "velocity_x": -118.8109130859375,
            "velocity_y": 46.988990783691406,
            "required_thrust_to_move": 5,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1355332352,
                "radius": 300,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 40,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Dark Autumn",
            "mass": 5000,
            "position_x": -107639.9765625,
            "position_y": -67520,
            "velocity_x": -7.682788848876953,
            "velocity_y": 85.71437072753906,
            "required_thrust_to_move": 6,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1023883840,
                "radius": 400,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 40,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Wam Sea",
            "mass": 10000,
            "position_x": 115799.9921875,
            "position_y": 61600.01171875,
            "velocity_x": 28.996124267578125,
            "velocity_y": -54.50893020629883,
            "required_thrust_to_move": 10,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1293120000,
                "radius": 800,
                "heightRange": 40,
                "waterHeight": 48,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 80,
                "metalClusters": 80,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 6,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Sangheilitat's Heresy",
            "mass": 5000,
            "position_x": 11300.017578125,
            "position_y": -25899.98828125,
            "velocity_x": 104.21553802490234,
            "velocity_y": -55.43351364135742,
            "required_thrust_to_move": 6,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 300630688,
                "radius": 350,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 40,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Cinadon's Landing",
            "mass": 5000,
            "position_x": 161100.046875,
            "position_y": -25999.93359375,
            "velocity_x": 8.819382667541504,
            "velocity_y": 54.646427154541016,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 852586496,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 25,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Erev",
            "mass": 5000,
            "position_x": -159800.015625,
            "position_y": 84499.96875,
            "velocity_x": -24.58481216430664,
            "velocity_y": -46.49296188354492,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 715656320,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 25,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}