{
    "name": "Zakuro Solitude",
    "description": "",
    "creator": "Zakuro",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Solitude",
            "mass": 10000,
            "position_x": 14299.990234375,
            "position_y": 19400.00390625,
            "velocity_x": -115.94149780273438,
            "velocity_y": 85.46192169189453,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 27868570,
                "radius": 900,
                "heightRange": 35,
                "waterHeight": 45,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Nonsolitude",
            "mass": 5000,
            "position_x": 17100,
            "position_y": 20500,
            "velocity_x": -68.80165100097656,
            "velocity_y": -34.53124237060547,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1537995648,
                "radius": 320,
                "heightRange": 50,
                "waterHeight": 41,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}