{
    "name": "Zax",
    "description": "Pax for FruitPAT",
    "creator": "edited by Zakuro",
    "version": "2.0.0",
    "planets": [
        {
            "name": "Zaeris",
            "mass": 50000,
            "position_x": 34200,
            "position_y": 100.0107421875,
            "velocity_x": -0.35358694195747375,
            "velocity_y": 120.91194152832031,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1623734656,
                "radius": 1300,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Zmare",
            "mass": 10000,
            "position_x": 43300,
            "position_y": -5900,
            "velocity_x": -83.71823120117188,
            "velocity_y": -5.524223327636719,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 206539,
                "radius": 500,
                "heightRange": 30.000003814697266,
                "waterHeight": 50,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 90,
                "heightAdjustments": []
            }
        },
        {
            "name": "Zignis",
            "mass": 10000,
            "position_x": 41700,
            "position_y": -199.98095703125,
            "velocity_x": -7.647593975067139,
            "velocity_y": -61.4434814453125,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1302664192,
                "radius": 500,
                "heightRange": 30.000003814697266,
                "waterHeight": 26.999998092651367,
                "waterDepth": 50,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 90,
                "heightAdjustments": []
            }
        },
        {
            "name": "Zpetram",
            "mass": 5000,
            "position_x": 30200.005859375,
            "position_y": -13299.9873046875,
            "velocity_x": 127.76580047607422,
            "velocity_y": 82.66740417480469,
            "required_thrust_to_move": 2,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1439939328,
                "radius": 300,
                "heightRange": 10,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 70,
                "heightAdjustments": []
            }
        },
        {
            "name": "ZXX-1304-Laser-Annihilaser",
            "mass": 35000,
            "position_x": -8900.0107421875,
            "position_y": 9999.990234375,
            "velocity_x": -144.36532592773438,
            "velocity_y": -128.4854278564453,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 809591040,
                "radius": 600,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}