{
    "name": "Zakuro Blast",
    "planets": [
        {
            "name": "Safe",
            "mass": 5000,
            "position_x": -16699.998046875,
            "position_y": 12800.001953125,
            "velocity_x": 93.77580261230469,
            "velocity_y": 122.34809112548828,
            "required_thrust_to_move": 90,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1024894080,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 35.000003814697266,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "1steroid",
            "mass": 5000,
            "position_x": 15569.49609375,
            "position_y": 2939.516357421875,
            "velocity_x": -32.95648193359375,
            "velocity_y": 174.55784606933594,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1869787136,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "2nderoid",
            "mass": 5000,
            "position_x": -14702.5703125,
            "position_y": 5785.71484375,
            "velocity_x": -65.14128112792969,
            "velocity_y": -165.5360565185547,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1620403328,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "3rderoid",
            "mass": 5000,
            "position_x": -12142.333984375,
            "position_y": -10158.9296875,
            "velocity_x": 114.03678894042969,
            "velocity_y": -136.30104064941406,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 150980992,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "4theroid",
            "mass": 5000,
            "position_x": -795.0939331054688,
            "position_y": 15779.0322265625,
            "velocity_x": -177.67193603515625,
            "velocity_y": -8.952767372131348,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1481124352,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "5theroid",
            "mass": 5000,
            "position_x": 7600,
            "position_y": -13900,
            "velocity_x": 155.87750244140625,
            "velocity_y": 85.22798919677734,
            "required_thrust_to_move": 90,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1557167360,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 9.999999046325684,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Blaster",
            "mass": 35000,
            "position_x": 7799.99755859375,
            "position_y": -13700.0009765625,
            "velocity_x": -154.7645721435547,
            "velocity_y": -88.11409759521484,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 600,
            "planet": {
                "seed": 801206848,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Safe Killer",
            "mass": 10000,
            "position_x": 11099.9970703125,
            "position_y": -17800.001953125,
            "velocity_x": 131.00216674804688,
            "velocity_y": 81.69233703613281,
            "required_thrust_to_move": 90,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1214120064,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}