{
    "name": "4U",
    "planets": [
        {
            "name": "SeeU",
            "mass": 10000,
            "position_x": 42500,
            "position_y": -42500,
            "velocity_x": -64.49381256103516,
            "velocity_y": -64.49381256103516,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 2,
            "planet": {
                "seed": 297470016,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "1U",
            "mass": 10000,
            "position_x": -60000.00390625,
            "position_y": 2399.9921875,
            "velocity_x": -3.64709210395813,
            "velocity_y": -91.17770385742188,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 600,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1169505792,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "2U",
            "mass": 10000,
            "position_x": -60000.0078125,
            "position_y": 1199.98828125,
            "velocity_x": -1.8251721858978271,
            "velocity_y": -91.25971221923828,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 600,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 94832024,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "3U",
            "mass": 10000,
            "position_x": -60000.0078125,
            "position_y": 0,
            "velocity_x": 0.000003990285222243983,
            "velocity_y": -91.2870864868164,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1500,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 114648760,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 40,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "4U",
            "mass": 10000,
            "position_x": -25999.99609375,
            "position_y": -200.0106658935547,
            "velocity_x": 7.2084784507751465,
            "velocity_y": 80.21168518066406,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 2400,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1898581248,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "4Ever",
            "mass": 50000,
            "position_x": -21399.99609375,
            "position_y": -300.006103515625,
            "velocity_x": 2.14255428314209,
            "velocity_y": -152.83192443847656,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 2400,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 361530240,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}