{
    "name": "Edge of the World",
    "planets": [
        {
            "name": "Edge of the World",
            "mass": 5000,
            "position_x": -0.02001953125,
            "position_y": 25200.00390625,
            "velocity_x": -140.85902404785156,
            "velocity_y": -0.00011805917893070728,
            "required_thrust_to_move": 6,
            "starting_planet": true,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 300,
            "max_spawn_delay": 1500,
            "planet": {
                "seed": 269466272,
                "radius": 625,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Z-01",
            "mass": 5000,
            "position_x": 0.002574147190898657,
            "position_y": 15800.001953125,
            "velocity_x": -177.8920135498047,
            "velocity_y": 0.00002120638055203017,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 600,
            "planet": {
                "seed": 518724960,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 35.000003814697266,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Z-02",
            "mass": 5000,
            "position_x": -18558.75,
            "position_y": 0,
            "velocity_x": 0.000007174724487413187,
            "velocity_y": -164.13856506347656,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 600,
            "planet": {
                "seed": 305407424,
                "radius": 300,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Z-03",
            "mass": 5000,
            "position_x": 21100,
            "position_y": -0.0018446205649524927,
            "velocity_x": 0.000006728811968059745,
            "velocity_y": 153.93727111816406,
            "required_thrust_to_move": 5,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 0,
            "max_spawn_delay": 900,
            "planet": {
                "seed": 1534922880,
                "radius": 350,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zakuro Finale",
            "mass": 35000,
            "position_x": -9000,
            "position_y": -9000,
            "velocity_x": 140.14939880371094,
            "velocity_y": -140.14939880371094,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 10,
            "max_spawn_delay": 10,
            "planet": {
                "seed": 1036771904,
                "radius": 500,
                "heightRange": 900,
                "waterHeight": 1200,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}