{
    "name": "Supercell",
    "planets": [
        {
            "name": "Supercell I",
            "mass": 50000,
            "position_x": -0.0002981220022775233,
            "position_y": 25000,
            "velocity_x": -141.42135620117188,
            "velocity_y": -0.000007868155989854131,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 342902048,
                "radius": 1750,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell Ia",
            "mass": 10000,
            "position_x": 0.03770823776721954,
            "position_y": 28800.0078125,
            "velocity_x": 115.07296752929688,
            "velocity_y": -0.0025620239321142435,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1306847744,
                "radius": 625,
                "heightRange": 35,
                "waterHeight": 30.000001907348633,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell Ib",
            "mass": 10000,
            "position_x": -0.05022488161921501,
            "position_y": 30200,
            "velocity_x": 77.8431396484375,
            "velocity_y": 0.002106940373778343,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 874643392,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 52,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell Ic",
            "mass": 10000,
            "position_x": -0.05291042849421501,
            "position_y": 31100,
            "velocity_x": 61.022705078125,
            "velocity_y": 0.0017470545135438442,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1129930112,
                "radius": 250,
                "heightRange": 35,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell Id",
            "mass": 10000,
            "position_x": 0.010932346805930138,
            "position_y": 31800,
            "velocity_x": 50.31986999511719,
            "velocity_y": -0.0003161551139783114,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1836009216,
                "radius": 250,
                "heightRange": 35,
                "waterHeight": 40,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell Ie",
            "mass": 10000,
            "position_x": 0.012885471805930138,
            "position_y": 32400,
            "velocity_x": 42.38230895996094,
            "velocity_y": -0.0003272923640906811,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 272781664,
                "radius": 250,
                "heightRange": 35,
                "waterHeight": 55,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Supercell If",
            "mass": 10000,
            "position_x": 0,
            "position_y": 33000,
            "velocity_x": 35.3553466796875,
            "velocity_y": -0.0000067286287048773374,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1572028672,
                "radius": 250,
                "heightRange": 35,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}