name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move files
        run: |
          mkdir -p pat-star-systems/ui/mods/jaoafa/stella/
          cp -r stella/* pat-star-systems/ui/mods/jaoafa/stella/
          jq '.version|="${{ github.event.release.tag_name }}"' modinfo.json > pat-star-systems/modinfo.json

      - name: Create maps list
        run: |
          chmod 777 ./.github/scripts/create-maps-list.sh
          ./.github/scripts/create-maps-list.sh

      - name: Zip
        run: |
          zip -r pat-star-systems pat-star-systems
          sha1sum -b pat-star-systems.zip > pat-star-systems.zip.sha1

      - name: Upload Release Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./pat-star-systems.zip
          asset_name: pat-star-systems.zip
          asset_content_type: application/zip

      - name: Upload Release SHA1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./pat-star-systems.zip.sha1
          asset_name: pat-star-systems.zip.sha1
          asset_content_type: text/plain

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install create-schema dependencies
        run: npm install genson-js

      - name: Create schema
        run: |
          mkdir -p schema
          node ./.github/scripts/create-schema.js
          sha1sum -b schema.json > schema.json.sha1

      - name: Upload Schema
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./schema.json
          asset_name: schema.json
          asset_content_type: application/json

      - name: Upload Schema SHA1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./schema.json.sha1
          asset_name: schema.json.sha1
          asset_content_type: text/plain
